---
spring:
  config.activate.on-profile: search

where-for-dinner:
  searchEvent:
    period: 5000

---
spring:
  config.activate.on-profile: crawler

where-for-dinner:
  randomsearcher:
    establishments:
    - diningName: Herford House
      phoneNumber: (816) 448-6007
      address: 8661 North Stoddard Ave
      locality: Kasnas City
      region: MO
      postalCode: 64153
      reservationURL: 'https://www.herefordhouse.com/reservations'
