where-for-dinner:
  notifications:
    email:
      enabled: true
      to: meyerg@vmware.com
      from: abareasol@gmail.com
      subject: 'You have new dining options available.'
      
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abareasol@gmail.com
    password: '{cipher}e2e24936e10b668462c3e1d93d97d7de1f3f8662763cc9651e36d8d054c645ae'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
