where-for-dinner:
  notifications:
    email:
      enabled: true
      to: meyerg@vmware.com
      from: gmeyer2@kc.rr.com
      subject: 'You have new dining options available.'
      
spring:
  mail:
    host: mail.twc.com
    port: 587
    username: gmeyer2@kc.rr.com
    password: '{cipher}16b1148dab352da5b83db4be00add086a6d286b566884cb879a1556301a5ef4e'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
