where-for-dinner:
  notifications:
    email:
      enabled: true
      to: meyerg@vmware.com
      from: abareasol@gmail.com
      subject: 'You have new dining options available.'
      
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: abareasol@gmail.com
    password: '{cipher}0265667ebdd7a0f49b8bad84fe68c04ebe272fbde4f218d2b3ddf29438e53300'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
